routes/web.php
<?php
Route::group(['middleware' => 'web'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/puslapis/{page}', 'PageController@pageShow')->name('pageShow');
    Route::get('/naujienos-puslapis/{slug}', 'PostController@postShow')->name('postShow');
    Route::post('sort', '\Rutorika\Sortable\SortableController@sort')->name('sort');
    Route::get('logout', 'HomeController@logout')->name('logout');

    //ajax
    Route::get('/ajax/product/{productId}', 'Api\ApiController@getProduct')->name('ajaxProduct');
});

Route::group(['middleware' => 'admin', 'prefix' => 'admin'], function() 
{
    Route::get('/', 'Admin\AdminController@index')->name('admin.home');

    Route::resource('users', 'Admin\Users\UsersController');
    Route::resource('categories', 'Admin\Categories\CategoriesController');
    Route::resource('pages', 'Admin\Pages\PagesController');
    Route::resource('products', 'Admin\Products\ProductsController');
    Route::resource('posts', 'Admin\Posts\PostsController');
    Route::resource('settings', 'Admin\Settings\SettingsController');

});

Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'permission'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getPermission() {
        return $this->attributes['permission'];
    }

    public function getName() {
        return $this->attributes['name'];
    }

    public function getAvatar() {
        return 'https://api.adorable.io/avatars/167/' . $this->attributes['email'] . '.png';
    }
}

app/Http/Controllers/Admin/Users/UsersController.php
<?php

namespace App\Http\Controllers\Admin\Users;

use App\Http\Requests\Users\UserCreateRequest;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(10);
        return view('admin.users.index')->with(array(
            'users' => $users
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return false;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserCreateRequest $request)
    {
        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password),
            'permission' => 1,
        ]);

        session()->flash('success', 'Naudotojas sėkmingai sukurtas.');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrfail($id);
        if($user) {
            return view('admin.users.show')->with(array(
                'user' => $user
            ));
        } else {
            return redirect()->back();
            
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrfail($id);
        if($user) {
            return view('admin.users.edit')->with(array(
                'user' => $user
            ));
        } else {
            session()->flash('error', 'Naudotojo nepavyko rasti.');
            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        if($user) {
            $user->name = $request->name;
            $user->email = $request->email;
            $user->permissions = 1;
            $user->save();

            session()->flash('success', 'Naudotojas sėkmingai atnaujintas.');
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrfail($id);
        if($user) {
            $user->delete();
        }
        
        return redirect()->back();
    }
}

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.master')
@section('content')
    @include('admin.includes.header',[
        'title' => 'Naudotojo redagavimas'
    ])

    <div class="content">
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title">Readguoti {{ $user->email }} naudotoją <a class="heading-elements-toggle"><i class="icon-more"></i></a></h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            <div class="panel-body">
                @include('admin.includes.alert')

                <form action="{{ route('users.update', $user->id) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}

                    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <label>Name</label>
                        <input type="text" class="form-control" value="{{ $user->name }}" placeholder="Slapyvardis" name="name">
                        <p class="help-block">{{ $errors->first('name', ':message') }}</p>
                    </div>

                    <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                        <label>El. paštas</label>
                        <input type="email" class="form-control" value="{{ $user->email }}" placeholder="El. paštas" name="email">
                        <p class="help-block">{{ $errors->first('name', ':message') }}</p>
                    </div>

                    <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                        <label>Slaptažodis</label>
                        <input type="password" class="form-control" value="{{ old('password') }}" placeholder="Slaptažodis" name="password">
                        <p class="help-block">{{ $errors->first('name', ':message') }}</p>
                    </div>

                    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <label>Pakartokite slaptažodis</label>
                        <input type="password" class="form-control" value="{{ old('repeat_password') }}" placeholder="Pakartokite slaptažodis" name="repeat_password">
                        <p class="help-block">{{ $errors->first('name', ':message') }}</p>
                    </div>

                    <button class="btn btn-primary">Atnaujinti</button>
                </form>
            </div>
        </div>
        <!-- /simple panel -->

    </div>
    <!-- /content area -->

@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.master')
@section('content')
    @include('admin.includes.header',[
        'title' => 'Naudotojai'
    ])

    <div class="content">
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title">Naudotojai <a class="heading-elements-toggle"><i class="icon-more"></i></a></h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            <div class="panel-body">
                @include('admin.includes.alert')

                <form action="{{ route('users.store') }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('POST') }}

                    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <label>Slapyvardis</label>
                        <input type="text" class="form-control" value="{{ old('name') }}" placeholder="Slapyvardis" name="name">
                        <p class="help-block">{{ $errors->first('name', ':message') }}</p>
                    </div>

                    <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                        <label>El. paštas</label>
                        <input type="email" class="form-control" value="{{ old('email') }}" placeholder="El. paštas" name="email">
                        <p class="help-block">{{ $errors->first('name', ':message') }}</p>
                    </div>

                    <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                        <label>Slaptažodis</label>
                        <input type="password" class="form-control" value="{{ old('password') }}" placeholder="Slaptažodis" name="password">
                        <p class="help-block">{{ $errors->first('name', ':message') }}</p>
                    </div>

                    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <label>Pakartokite slaptažodį</label>
                        <input type="password" class="form-control" value="{{ old('repeat_password') }}" placeholder="Pakartokite slaptažodį" name="repeat_password">
                        <p class="help-block">{{ $errors->first('name', ':message') }}</p>
                    </div>s

                    <button class="btn btn-primary">Pridėti</button>
                </form>
            </div>

            @if(!$users->isEmpty())
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td>#</td>
                                <td>Slapyvardis</td>
                                <td>El. pašto adreasas</td>
                                <td>Sukurtas</td>
                                <td>Atnaujintas</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->created_at }}</td>
                                    <td>{{ $user->updated_at }}</td>
                                    <td><a href="{{ route('users.edit', $user->id) }}" class="btn btn-primary">Redaguoti</a></td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="panel-body">
                    <div class="text-center">
                        {{ $users->links() }}
                    </div>
                </div>
            @else
                <div class="panel-body">
                    <div class="alert-danger alert">Naudotoju nėra.</div>
                </div>
            @endif
        </div>
        <!-- /simple panel -->

    </div>
    <!-- /content area -->

@endsection