routes/web.php
<?php
Route::group(['middleware' => 'web'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/puslapis/{page}', 'PageController@pageShow')->name('pageShow');
    Route::get('/naujienos-puslapis/{slug}', 'PostController@postShow')->name('postShow');
    Route::post('sort', '\Rutorika\Sortable\SortableController@sort')->name('sort');
    Route::get('logout', 'HomeController@logout')->name('logout');

    //ajax
    Route::get('/ajax/product/{productId}', 'Api\ApiController@getProduct')->name('ajaxProduct');
});

Route::group(['middleware' => 'admin', 'prefix' => 'admin'], function() 
{
    Route::get('/', 'Admin\AdminController@index')->name('admin.home');

    Route::resource('users', 'Admin\Users\UsersController');
    Route::resource('categories', 'Admin\Categories\CategoriesController');
    Route::resource('pages', 'Admin\Pages\PagesController');
    Route::resource('products', 'Admin\Products\ProductsController');
    Route::resource('posts', 'Admin\Posts\PostsController');
    Route::resource('settings', 'Admin\Settings\SettingsController');

});

Auth::routes();

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use \Rutorika\Sortable\SortableTrait;
    protected $fillable = ['name', 'icon'];

    public function getProducts()
    {
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/Admin/Categories/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin\Categories;

use App\Category;
use App\Http\Requests\Categories\CategoriesCreateRequest;
use App\Http\Requests\Categories\CategoriesEditRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::sorted()->get();
        return view('admin.categories.index')->with(array(
            'categories' => $categories
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoriesCreateRequest $request)
    {
        if($request->hasFile('icon')) {

            $destinationPath = base_path() . '/public/uploads/categories/icons/'; // upload path

            if($request->file('icon')) {
                $file = $request->file('icon');
                $file_name_ext = $file->getClientOriginalExtension();
                $generated_id = uniqid();

                $ul = $generated_id . '.' . strtolower($file_name_ext);

                // uploading

                $img = Image::make($file);
                $img->save($destinationPath . $ul);

                if(file_exists($destinationPath . $ul)) {
                    Category::create([
                        'name' => $request->name,
                        'icon' => $ul,
                    ]);

                    session()->flash('success', 'Kategorija sėkmingai sukurta.');
                } else {
                    session()->flash('error', 'Kategorija nepatalpinta.');
                }
            }
        } else {
            session()->flash('error', 'Naujiena nepatalpinta.');
        }

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $category = Category::find($category->id);
        if($category) {
            return view('admin.categories.edit')->with(array(
                'category' => $category
            ));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoriesEditRequest $request, Category $category)
    {
        $category = Category::find($category->id);
        if($category) {
            $category->name = $request->name;

            if($request->hasFile('icon')) {

                $destinationPath = base_path() . '/public/uploads/categories/icons/'; // upload path

                if($request->file('icon')) {
                    $file = $request->file('icon');
                    $file_name_ext = $file->getClientOriginalExtension();
                    $generated_id = uniqid();

                    $ul = $generated_id . '.' . strtolower($file_name_ext);

                    // uploading

                    $img = Image::make($file);
                    $img->save($destinationPath . $ul);

                    if(file_exists($destinationPath . $ul)) {

                        $category->icon = $ul;

                        session()->flash('success', 'Kategorija sėkmingai sukurta.');
                    } else {
                        session()->flash('error', 'Kategorija nepatalpinta.');
                    }
                }
            } else {
                session()->flash('error', 'Naujiena nepatalpinta.');
            }

            $category->save();

            session()->flash('success', 'Kategorija sėkmingai atnaujinta.');
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category = Category::find($category->id);
        if($category) {
            $category->delete();

            session()->flash('success', 'Kategorija sekmingai ištrinta.');
        }

        return redirect()->back();
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')
@section('content')
    @include('admin.includes.header',[
        'title' => 'Kurti kategorija'
    ])
    <!-- Content area -->
    <div class="content">
        <!-- Simple panel -->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title">Kurti kateogrija<a class="heading-elements-toggle"><i class="icon-box"></i></a></h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            <div class="panel-body">
                @include('admin.includes.alert')
                <form method="post" action="{{ route('categories.store') }}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('POST') }}

                    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                        <label>Pavadinimas</label>
                        <input class="form-control" name="name" placeholder="Pavadinimas">
                        <p class="help-block">{{ $errors->has('name') ? $errors->first('name') : '' }}</p>
                    </div>

                    <div class="form-group {{ $errors->has('icon') ? ' has-error' : '' }}">
                        <label>Paveiksliukas</label>
                        <input type="file" name="icon" class="form-control">
                        <p class="help-block">{{ $errors->has('icon') ? $errors->first('icon') : '' }}</p>
                    </div>

                    <button class="btn btn-primary btn-sm">Kurti</button>
                    <a href="{{ route('categories.index') }}" class="btn btn-default btn-sm">Grįžti atgal</a>
                </form>
            </div>
        </div>
        <!-- /simple panel -->

    </div>
    <!-- /content area -->
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')
@section('content')
    @include('admin.includes.header',[
        'title' => 'Redaguoti kategorija',
        'description' => 'Puslapio kategorija'
    ])
    <div class="content">
        <div class="panel panel-flat">
            <div class="panel-body">

                @include('admin.includes.alert')

                <form action="{{ route('categories.update', $category->id) }}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}

                    <div class="form-group {{ ($errors->has('name') ? 'has-error' : '') }}">
                        <label>Pavadinimas</label>
                        <input class="form-control input-sm" placeholder="Pavadinimas" name="name" value="{{ $category->name }}">
                        <p class="help-block">{{ $errors->first('name', ':message') }}</p>
                    </div>
                    
                    <div class="text-center">
                        <img src="{{ asset('uploads/categories/icons/' . ) }}">
                    </div>

                    <div class="form-group {{ $errors->has('icon') ? ' has-error' : '' }}">
                        <label>Paveiksliukas</label>
                        <input type="file" name="icon" class="form-control">
                        <p class="help-block">{{ $errors->has('icon') ? $errors->first('icon') : '' }}</p>
                    </div>

                    <button type="submit" class="btn btn-primary btn-sm">Redaugoti</button>
                    <a class="btn btn-default btn-sm" href="{{ route('categories.index') }}">Grįžti</a>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')
@section('content')
    @include('admin.includes.header',[
        'title' => 'Kategorijos',
        'description' => 'Svetainės kategoriju koregavimas.',
        'actions' => [
            [
                'title' => 'Kurti kategorija',
                'route' => route('categories.create')
            ]
        ]
    ])
    <!-- Content area -->
    <div class="content">
        <!-- Simple panel -->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title">Kategorijos<a class="heading-elements-toggle"><i class="icon-more"></i></a></h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            @if(!$categories->isEmpty())
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <td></td>
                            <td>#</td>
                            <td>Pavadinimas</td>
                            <td></td>
                            <td></td>
                        </tr>
                        </thead>
                        <tbody class="sortable" data-entityname="categories">
                        @foreach($categories as $category)
                            <tr class="small" data-itemId="{{ $category->id }}">
                                <td class="sortable-handle"><span class="icon-sort"></span></td>
                                <td>{{ $category->id }}</td>
                                <td>{{ $category->name }}</td>
                                <td><a href="{{ route('categories.edit', $category->id) }}" class="btn btn-primary">Redaguoti</a></td>
                                <td>
                                    <form action="{{ route('categories.destroy', $category->id) }}" method="post">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button onclick="return confirm('Ar tikrai norite ištrinti kategorija?');" type="submit" class="btn btn-danger btn-sm">Pašalinti</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            @else
                <div class="panel-body">
                    <div class="alert alert-danger">Kategoriju nera.</div>
                </div>
            @endif
        </div>
        <!-- /simple panel -->

    </div>
    <!-- /content area -->

@endsection