routes/web.php
<?php
Route::group(['middleware' => 'web'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/puslapis/{page}', 'PageController@pageShow')->name('pageShow');
    Route::get('/naujienos-puslapis/{slug}', 'PostController@postShow')->name('postShow');
    Route::post('sort', '\Rutorika\Sortable\SortableController@sort')->name('sort');
    Route::get('logout', 'HomeController@logout')->name('logout');

    //ajax
    Route::get('/ajax/product/{productId}', 'Api\ApiController@getProduct')->name('ajaxProduct');
});

Route::group(['middleware' => 'admin', 'prefix' => 'admin'], function() 
{
    Route::get('/', 'Admin\AdminController@index')->name('admin.home');

    Route::resource('users', 'Admin\Users\UsersController');
    Route::resource('categories', 'Admin\Categories\CategoriesController');
    Route::resource('pages', 'Admin\Pages\PagesController');
    Route::resource('products', 'Admin\Products\ProductsController');
    Route::resource('posts', 'Admin\Posts\PostsController');
    Route::resource('settings', 'Admin\Settings\SettingsController');

});

Auth::routes();

resources/views/admin/includes/alert.blade.php
@if(Session::has('success'))
    <div class="alert alert-success">{{ Session::get('success') }}</div>
@endif

@if(Session::has('error'))
    <div class="alert alert-danger">{{ session('error') }}</div>
@endif

resources/views/admin/includes/header.blade.php
<div class="page-header page-header" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">
    <div class="page-header-content">
        <div class="page-title">
            <h5>
                <i class="icon-arrow-left52 position-left"></i>
                @if(!empty($title))
                    <span class="text-semibold">{{ $title }}</span>
                @endif

                @if(!empty($description))
                    <small class="display-block">{{ $description }}</small>
                @endif
            </h5>
            <a class="heading-elements-toggle"><i class="icon-more"></i></a></div>

        <div class="heading-elements">
            <button class="btn btn-link btn-icon btn-sm heading-btn"><i class="icon-gear"></i></button>
        </div>
    </div>

    <div class="breadcrumb-line"><a class="breadcrumb-elements-toggle"><i class="icon-menu-open"></i></a>
        <ul class="breadcrumb">
            <li><a href="{{ route('home') }}"><i class="icon-home2 position-left"></i> Home</a></li>
            <li><a href="#">Current</a></li>
        </ul>

        <ul class="breadcrumb-elements">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-cog5 position-left"></i> Veiksmai
                    <span class="caret"></span>
                </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="#" onclick="window.print();"><i class="icon-printer pull-right"></i> Spausdinti</a></li>
                    @if(!empty($actions))
                        @foreach($actions as $action)
                            <li>
                                <a href="{{ (empty($action['route']) ? '#' : $action['route']) }}">
                                    <i class="{{ (empty($action['icon']) ? 'icon-more' : $action['icon']) }} pull-right"></i>
                                    {{ (empty($action['title']) ? 'Not defined' : $action['title']) }}
                                </a>
                            </li>
                        @endforeach
                    @endif
                </ul>
            </li>
        </ul>
    </div>
</div>
<!-- /page header -->

resources/views/admin/includes/sidebar.blade.php
<div class="sidebar sidebar-main">
	<div class="sidebar-content">

		<!-- User menu -->
		<div class="sidebar-user">
			<div class="category-content">
				<div class="media">
					<a href="#" class="media-left"><img src="{{ asset(Auth::user()->getAvatar()) }}" class="img-circle img-sm" alt=""></a>
					<div class="media-body">
						<span class="media-heading text-semibold">{{ Auth::user()->getName() }}</span>
						<div class="text-size-mini text-muted">
							<i class="icon-user text-size-small"></i> {{ Auth::user()->getPermission() }}&nbsp;
						</div>
					</div>

					<div class="media-right media-middle">
						<ul class="icons-list">
							<li>
								<a href="#"><i class="icon-cog3"></i></a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<!-- /user menu -->


		<!-- Main navigation -->
		<div class="sidebar-category sidebar-category-visible">
			<div class="category-content no-padding">
				<ul class="navigation navigation-main navigation-accordion">
					<!-- Main -->
					<li class="navigation-header"><span>Pagrindiniai</span> <i class="icon-menu" title="" data-original-title="Pagrindiniai"></i></li>

                    <li><a href="{{ route('admin.home') }}"><i class="icon-home4"></i> <span>Skydelis</span></a></li>
                    <li><a href="{{ route('users.index') }}"><i class="icon-users"></i> <span>Naudotojai</span></a></li>
                    <li><a href="{{ route('pages.index') }}"><i class="icon-box"></i> <span>Puslapiai</span></a></li>
                    <li><a href="{{ route('categories.index') }}"><i class="icon-library2"></i> <span>Kategorijos</span></a></li>
                    <li><a href="{{ route('products.index') }}"><i class="icon-accessibility"></i> <span>Produktai</span></a></li>
                    <li><a href="{{ route('posts.index') }}"><i class="icon-list"></i> <span>Naujienos</span></a></li>
                    <li><a href="{{ route('settings.index') }}"><i class="icon-gear"></i> <span>Nustatymai</span></a></li>
				</ul>
			</div>
		</div>
		<!-- /main navigation -->

	</div>
</div>

resources/views/admin/includes/topbar.blade.php
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        <a class="navbar-brand" href="{{ route('admin.home') }}"><img src="{{ asset('administration/images/logo_light.png') }}" alt=""></a>

        <ul class="nav navbar-nav visible-xs-block">
            <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
            <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>
    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile">
        <ul class="nav navbar-nav">
            <li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">

            <li class="dropdown dropdown-user">
                <a class="dropdown-toggle" data-toggle="dropdown">
                    <img src="{{ asset(Auth::user()->getAvatar()) }}" alt="">
                    <span>{{ Auth::user()->getName() }}</span>
                    <i class="caret"></i>
                </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="{{ route('home') }}"><i class="icon-arrow-down-left2"></i> Grįžti į svetainę</a></li>
                    <li><a href="{{ route('logout') }}"><i class="icon-arrow-down-right2"></i> Atsijungti</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>